// ============================================================
// ReportsPage — List of generated forensic reports
// ============================================================
import { FileText, Download, ExternalLink } from 'lucide-react'

const MOCK_REPORTS = [
  { id: 'rpt-001', case_number: 'VRD-2025-000001', type: 'forensic_summary', generated_by: 'Arjun Thapa', generated_at: '2025-05-23T10:00:00Z', hash: 'b4c8d2e1f' },
  { id: 'rpt-002', case_number: 'VRD-2025-000003', type: 'full_report', generated_by: 'Arjun Thapa', generated_at: '2025-05-24T14:30:00Z', hash: 'f2a7c9e3d' },
]

export default function ReportsPage() {
  return (
    <div className="space-y-5 animate-slide-up">
      <div>
        <h1 className="text-h2 font-bold text-text-primary">Forensic Reports</h1>
        <p className="text-body-sm text-text-muted mt-1">{MOCK_REPORTS.length} reports generated</p>
      </div>

      {MOCK_REPORTS.length === 0 ? (
        <div className="card-base p-16 text-center">
          <FileText className="w-10 h-10 text-text-disabled mx-auto mb-3" />
          <p className="text-h4 font-semibold text-text-primary">No reports yet</p>
          <p className="text-body-sm text-text-muted mt-1">Reports are generated from the Case Detail page.</p>
        </div>
      ) : (
        <div className="card-base overflow-hidden">
          <table className="w-full">
            <thead>
              <tr className="table-header">
                <th className="text-left px-4 py-3">Case</th>
                <th className="text-left px-4 py-3 hidden md:table-cell">Report Type</th>
                <th className="text-left px-4 py-3 hidden sm:table-cell">Generated By</th>
                <th className="text-left px-4 py-3">Date</th>
                <th className="text-right px-4 py-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {MOCK_REPORTS.map(report => (
                <tr key={report.id} className="table-row">
                  <td className="px-4 py-3">
                    <span className="font-mono-data text-body-sm text-accent-primary">{report.case_number}</span>
                    <p className="hash-display text-[10px] mt-1 w-fit">{report.hash}...</p>
                  </td>
                  <td className="px-4 py-3 hidden md:table-cell">
                    <span className="text-body-sm text-text-secondary capitalize">{report.type.replace(/_/g, ' ')}</span>
                  </td>
                  <td className="px-4 py-3 hidden sm:table-cell">
                    <span className="text-body-sm text-text-secondary">{report.generated_by}</span>
                  </td>
                  <td className="px-4 py-3">
                    <span className="text-caption text-text-muted">{new Date(report.generated_at).toLocaleDateString()}</span>
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      id={`reports-download-${report.id}`}
                      className="btn-secondary text-caption gap-1.5"
                    >
                      <Download className="w-3.5 h-3.5" /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
