// ============================================================
// mockData — Sample data for Phase 1 UI development
// ============================================================
import type { Case } from '@/types'

export const MOCK_CASES: Case[] = [
  {
    id: 'case-001',
    case_number: 'VRD-2025-000001',
    title: 'Deepfake video circulating on social media',
    description: 'A fabricated video of a local politician was shared widely on Facebook.',
    complaint_type: 'deepfake_video',
    status: 'in_review',
    priority: 'high',
    assigned_to: 'usr-002',
    assigned_to_name: 'Arjun Thapa',
    contact_email: 'reporter@example.com',
    created_at: '2025-05-20T10:30:00Z',
    updated_at: '2025-05-22T14:00:00Z',
    evidence_count: 2,
  },
  {
    id: 'case-002',
    case_number: 'VRD-2025-000002',
    title: 'Voice clone used in phone scam',
    description: 'Victim received a call from an apparent clone of their bank manager\'s voice requesting fund transfer.',
    complaint_type: 'voice_clone',
    status: 'pending',
    priority: 'critical',
    created_at: '2025-05-21T08:15:00Z',
    updated_at: '2025-05-21T08:15:00Z',
    evidence_count: 1,
  },
  {
    id: 'case-003',
    case_number: 'VRD-2025-000003',
    title: 'Forged citizenship document submitted for loan',
    description: 'Bank reported a suspicious citizenship document that appears digitally altered.',
    complaint_type: 'fake_document',
    status: 'analysis_complete',
    priority: 'medium',
    assigned_to: 'usr-002',
    assigned_to_name: 'Arjun Thapa',
    created_at: '2025-05-18T11:45:00Z',
    updated_at: '2025-05-23T09:00:00Z',
    evidence_count: 3,
  },
  {
    id: 'case-004',
    case_number: 'VRD-2025-000004',
    title: 'AI-generated profile used in romance scam',
    description: 'Multiple victims reported losing money to an account using a synthetic AI-generated face.',
    complaint_type: 'synthetic_identity',
    status: 'report_generated',
    priority: 'high',
    assigned_to: 'usr-002',
    assigned_to_name: 'Arjun Thapa',
    created_at: '2025-05-15T14:30:00Z',
    updated_at: '2025-05-24T10:00:00Z',
    evidence_count: 5,
  },
  {
    id: 'case-005',
    case_number: 'VRD-2025-000005',
    title: 'Deepfake image used in defamation campaign',
    description: 'Fabricated intimate image of a teacher shared in parent WhatsApp groups.',
    complaint_type: 'deepfake_image',
    status: 'closed',
    priority: 'high',
    assigned_to: 'usr-002',
    assigned_to_name: 'Arjun Thapa',
    created_at: '2025-05-10T09:00:00Z',
    updated_at: '2025-05-25T16:00:00Z',
    evidence_count: 4,
  },
]
